import type {
  ActivityItem,
  AdminOverview,
  AdminUser,
  AnalyticsBundle,
  ChatMessageData,
  Concept,
  Material,
  Project,
  QuizQuestion,
  Recommendation,
  Space,
  SystemService,
  User,
} from "./types";

export const currentUser: User = {
  id: "u_1",
  name: "Yuvtej Sharma",
  email: "yuvtej@studymate.ai",
  role: "admin",
  avatarInitials: "YS",
  joinedAt: "2026-01-14",
};

export const spaces: Space[] = [
  {
    id: "sp_cs",
    name: "Computer Science",
    description: "Core CS foundations: data structures, algorithms and systems.",
    icon: "Cpu",
    projectCount: 8,
    averageProgress: 72,
    materials: 21,
    studyTimeHours: 46.5,
    averageMastery: 74,
    lastActivity: "Today",
  },
  {
    id: "sp_ml",
    name: "Machine Learning",
    description: "Supervised learning, model evaluation and deep learning basics.",
    icon: "Brain",
    projectCount: 4,
    averageProgress: 58,
    materials: 11,
    studyTimeHours: 22.0,
    averageMastery: 61,
    lastActivity: "Yesterday",
  },
  {
    id: "sp_math",
    name: "Mathematics",
    description: "Linear algebra, probability and discrete mathematics.",
    icon: "Sigma",
    projectCount: 3,
    averageProgress: 44,
    materials: 7,
    studyTimeHours: 12.5,
    averageMastery: 49,
    lastActivity: "3 days ago",
  },
];

export const projects: Project[] = [
  {
    id: "pr_java_dsa",
    spaceId: "sp_cs",
    name: "Java Data Structures & Algorithms",
    description: "Arrays, stacks, queues, sliding window patterns and tree traversals.",
    subject: "Computer Science",
    progress: 68,
    masteryScore: 76,
    conceptsMastered: 12,
    conceptCount: 18,
    materialCount: 3,
    quizAccuracy: 82,
    studyTimeHours: 18.5,
    status: "in-progress",
    lastActivity: "Today",
  },
  {
    id: "pr_ml_foundations",
    spaceId: "sp_ml",
    name: "Machine Learning Foundations",
    description: "Regression, classification, bias-variance and evaluation metrics.",
    subject: "Machine Learning",
    progress: 42,
    masteryScore: 58,
    conceptsMastered: 6,
    conceptCount: 14,
    materialCount: 2,
    quizAccuracy: 71,
    studyTimeHours: 9.5,
    status: "needs-review",
    lastActivity: "Yesterday",
  },
  {
    id: "pr_os",
    spaceId: "sp_cs",
    name: "Operating Systems",
    description: "Processes, scheduling, memory management and concurrency.",
    subject: "Computer Science",
    progress: 91,
    masteryScore: 88,
    conceptsMastered: 15,
    conceptCount: 16,
    materialCount: 4,
    quizAccuracy: 89,
    studyTimeHours: 14.0,
    status: "completed",
    lastActivity: "2 days ago",
  },
  {
    id: "pr_linear_algebra",
    spaceId: "sp_math",
    name: "Linear Algebra",
    description: "Vectors, matrices, eigenvalues and decompositions.",
    subject: "Mathematics",
    progress: 35,
    masteryScore: 47,
    conceptsMastered: 4,
    conceptCount: 12,
    materialCount: 2,
    quizAccuracy: 64,
    studyTimeHours: 6.5,
    status: "needs-review",
    lastActivity: "4 days ago",
  },
];

export const materials: Material[] = [
  {
    id: "m_1",
    projectId: "pr_java_dsa",
    name: "Java DSA Notes.pdf",
    sizeMb: 4.2,
    pages: 128,
    status: "ready",
    uploadedAt: "2026-09-02",
  },
  {
    id: "m_2",
    projectId: "pr_java_dsa",
    name: "Stack Problems.pdf",
    sizeMb: 1.8,
    pages: 42,
    status: "processing",
    progress: 64,
    uploadedAt: "2026-09-10",
  },
  {
    id: "m_3",
    projectId: "pr_java_dsa",
    name: "Sliding Window.pdf",
    sizeMb: 2.4,
    pages: 56,
    status: "ready",
    uploadedAt: "2026-08-28",
  },
  {
    id: "m_4",
    projectId: "pr_java_dsa",
    name: "Tree Traversals (scan).pdf",
    sizeMb: 9.1,
    pages: 0,
    status: "failed",
    error: "Text extraction failed — the PDF appears to be a low-quality scan.",
    uploadedAt: "2026-09-09",
  },
  {
    id: "m_5",
    projectId: "pr_ml_foundations",
    name: "ML Lecture Notes.pdf",
    sizeMb: 6.7,
    pages: 214,
    status: "ready",
    uploadedAt: "2026-08-21",
  },
  {
    id: "m_6",
    projectId: "pr_ml_foundations",
    name: "Model Evaluation.pdf",
    sizeMb: 2.1,
    pages: 38,
    status: "ready",
    uploadedAt: "2026-09-01",
  },
];

export const concepts: Concept[] = [
  {
    id: "c_arrays",
    projectId: "pr_java_dsa",
    name: "Arrays",
    mastery: 92,
    level: "Mastered",
    quizzesTaken: 6,
    assessmentsTaken: 2,
    tutorQuestions: 9,
    lastPracticed: "Today",
    summary: "Contiguous storage, index math, prefix sums and in-place manipulation.",
  },
  {
    id: "c_hashmap",
    projectId: "pr_java_dsa",
    name: "HashMap",
    mastery: 88,
    level: "Mastered",
    quizzesTaken: 5,
    assessmentsTaken: 1,
    tutorQuestions: 7,
    lastPracticed: "Yesterday",
    summary: "Hashing, collision handling and amortised O(1) lookups.",
  },
  {
    id: "c_stack",
    projectId: "pr_java_dsa",
    name: "Stack",
    mastery: 78,
    level: "Strong",
    quizzesTaken: 4,
    assessmentsTaken: 2,
    tutorQuestions: 12,
    lastPracticed: "Today",
    summary: "LIFO structure, monotonic stacks and next-greater-element patterns.",
  },
  {
    id: "c_queue",
    projectId: "pr_java_dsa",
    name: "Queue",
    mastery: 72,
    level: "Strong",
    quizzesTaken: 3,
    assessmentsTaken: 1,
    tutorQuestions: 4,
    lastPracticed: "2 days ago",
    summary: "FIFO structure, deques and BFS traversal support.",
  },
  {
    id: "c_sliding_window",
    projectId: "pr_java_dsa",
    name: "Sliding Window",
    mastery: 61,
    level: "Developing",
    quizzesTaken: 4,
    assessmentsTaken: 1,
    tutorQuestions: 8,
    lastPracticed: "Today",
    summary: "Fixed and variable windows for subarray optimisation problems.",
  },
  {
    id: "c_two_pointers",
    projectId: "pr_java_dsa",
    name: "Two Pointers",
    mastery: 66,
    level: "Developing",
    quizzesTaken: 3,
    assessmentsTaken: 0,
    tutorQuestions: 5,
    lastPracticed: "3 days ago",
    summary: "Opposing and same-direction pointer scans on sorted inputs.",
  },
  {
    id: "c_binary_trees",
    projectId: "pr_java_dsa",
    name: "Binary Trees",
    mastery: 45,
    level: "Needs Review",
    quizzesTaken: 2,
    assessmentsTaken: 0,
    tutorQuestions: 3,
    lastPracticed: "5 days ago",
    summary: "Traversals, recursion patterns and height/depth reasoning.",
  },
];

export const tutorConversation: ChatMessageData[] = [
  {
    id: "msg_1",
    role: "user",
    content: "Explain monotonic stack with an example.",
    createdAt: "10:12",
  },
  {
    id: "msg_2",
    role: "assistant",
    grounded: true,
    content:
      "Based on your uploaded material, a monotonic stack is a stack whose elements always stay in sorted order — either increasing or decreasing — as you push and pop.\n\nThe key idea: before pushing a new element, you pop everything that would break the ordering. Each popped element has just found its 'next greater' (or smaller) element, which is why the pattern solves those problems in a single O(n) pass.\n\nExample — next greater element for [2, 1, 5, 6, 2, 3]:\n1. Push 2. Stack: [2]\n2. Push 1 (1 < 2, ordering holds). Stack: [2, 1]\n3. See 5 → pop 1 and 2, their answer is 5. Stack: [5]\n4. See 6 → pop 5, answer is 6. Stack: [6]\n\nEach element is pushed and popped at most once, giving linear time.",
    citations: [
      {
        id: "cit_1",
        document: "Java DSA Notes.pdf",
        page: 24,
        excerpt:
          "A monotonic stack maintains its elements in strictly increasing or decreasing order; violating elements are popped before the new element is pushed.",
      },
      {
        id: "cit_2",
        document: "Java DSA Notes.pdf",
        page: 27,
        excerpt:
          "Because every element enters and leaves the stack at most once, next-greater-element runs in O(n) time and O(n) space.",
      },
    ],
    createdAt: "10:12",
  },
  {
    id: "msg_3",
    role: "user",
    content: "How does the Transformer attention mechanism work?",
    createdAt: "10:18",
  },
  {
    id: "msg_4",
    role: "assistant",
    unsupported: true,
    content:
      "I couldn't find enough information about this topic in your uploaded materials for this project.",
    suggestions: ["Monotonic Stack", "Sliding Window", "Binary Trees"],
    createdAt: "10:18",
  },
];

export const quizQuestions: QuizQuestion[] = [
  {
    id: "q1",
    concept: "Stack",
    difficulty: "Medium",
    prompt: "What is the primary advantage of a monotonic stack?",
    options: [
      { id: "a", text: "It sorts the input array in O(n) time." },
      { id: "b", text: "It finds next greater/smaller elements in a single linear pass." },
      { id: "c", text: "It reduces memory usage to O(1)." },
      { id: "d", text: "It guarantees balanced tree height." },
    ],
    correctOptionId: "b",
    explanation:
      "Each element is pushed and popped at most once, so next-greater-element queries resolve in O(n).",
  },
  {
    id: "q2",
    concept: "Sliding Window",
    difficulty: "Medium",
    prompt: "When is a variable-size sliding window preferred over a fixed-size window?",
    options: [
      { id: "a", text: "When the window length is given in the problem statement." },
      { id: "b", text: "When the array is already sorted." },
      { id: "c", text: "When the window must satisfy a constraint such as a target sum." },
      { id: "d", text: "When the input contains negative numbers only." },
    ],
    correctOptionId: "c",
    explanation:
      "Variable windows expand and shrink until a constraint is satisfied, unlike fixed-length scans.",
  },
  {
    id: "q3",
    concept: "Arrays",
    difficulty: "Easy",
    prompt: "What is the time complexity of computing a prefix sum array?",
    options: [
      { id: "a", text: "O(1)" },
      { id: "b", text: "O(log n)" },
      { id: "c", text: "O(n)" },
      { id: "d", text: "O(n log n)" },
    ],
    correctOptionId: "c",
    explanation: "A single pass accumulates the running total for each index.",
  },
  {
    id: "q4",
    concept: "HashMap",
    difficulty: "Medium",
    prompt: "Why is HashMap lookup described as amortised O(1) rather than guaranteed O(1)?",
    options: [
      { id: "a", text: "Because hashing is always slower than comparison." },
      { id: "b", text: "Because collisions and resizing can make individual operations slower." },
      { id: "c", text: "Because keys must be sorted before lookup." },
      { id: "d", text: "Because Java caches only the last inserted key." },
    ],
    correctOptionId: "b",
    explanation: "Collision chains and rehashing make worst-case single operations costlier.",
  },
  {
    id: "q5",
    concept: "Queue",
    difficulty: "Easy",
    prompt: "Which traversal relies on a queue?",
    options: [
      { id: "a", text: "Depth-first search" },
      { id: "b", text: "Breadth-first search" },
      { id: "c", text: "Inorder traversal via recursion" },
      { id: "d", text: "Binary search" },
    ],
    correctOptionId: "b",
    explanation: "BFS explores level by level using FIFO ordering.",
  },
  {
    id: "q6",
    concept: "Sliding Window",
    difficulty: "Hard",
    prompt:
      "For the longest substring without repeating characters, what does the left pointer do?",
    options: [
      { id: "a", text: "It resets to zero after every duplicate." },
      { id: "b", text: "It advances past the previous occurrence of the duplicate character." },
      { id: "c", text: "It always moves one step per iteration." },
      { id: "d", text: "It stays fixed while the right pointer scans." },
    ],
    correctOptionId: "b",
    explanation: "Jumping the left pointer keeps the window valid without rescanning.",
  },
  {
    id: "q7",
    concept: "Binary Trees",
    difficulty: "Medium",
    prompt: "Which traversal of a binary search tree produces sorted output?",
    options: [
      { id: "a", text: "Preorder" },
      { id: "b", text: "Postorder" },
      { id: "c", text: "Inorder" },
      { id: "d", text: "Level order" },
    ],
    correctOptionId: "c",
    explanation: "Inorder visits left subtree, node, then right subtree.",
  },
  {
    id: "q8",
    concept: "Two Pointers",
    difficulty: "Easy",
    prompt: "Two pointers moving inward requires which precondition most often?",
    options: [
      { id: "a", text: "A sorted array" },
      { id: "b", text: "A hash map of counts" },
      { id: "c", text: "A balanced tree" },
      { id: "d", text: "A priority queue" },
    ],
    correctOptionId: "a",
    explanation: "Sorted order lets you decide which pointer to move.",
  },
  {
    id: "q9",
    concept: "Stack",
    difficulty: "Medium",
    prompt: "In a decreasing monotonic stack, when do you pop?",
    options: [
      { id: "a", text: "When the incoming element is smaller than the top." },
      { id: "b", text: "When the incoming element is greater than the top." },
      { id: "c", text: "Only at the end of the scan." },
      { id: "d", text: "Never — you only push." },
    ],
    correctOptionId: "b",
    explanation: "A larger incoming value breaks the decreasing invariant, so smaller tops pop.",
  },
  {
    id: "q10",
    concept: "Arrays",
    difficulty: "Hard",
    prompt: "Which technique answers many range-sum queries fastest after preprocessing?",
    options: [
      { id: "a", text: "Recomputing the sum per query" },
      { id: "b", text: "Prefix sums" },
      { id: "c", text: "Sorting the array" },
      { id: "d", text: "Two pointers" },
    ],
    correctOptionId: "b",
    explanation: "Prefix sums answer each range query in O(1) after O(n) preprocessing.",
  },
];

export const recommendations: Recommendation[] = [
  {
    id: "rec_1",
    title: "Review Monotonic Stack",
    reason: "Your recent quiz performance shows this concept needs reinforcement.",
    priority: "High",
    estimatedMinutes: 15,
    type: "review",
    projectId: "pr_java_dsa",
  },
  {
    id: "rec_2",
    title: "Review Sliding Window",
    reason: "Your recent assessment indicates this concept needs reinforcement.",
    priority: "High",
    estimatedMinutes: 20,
    type: "review",
    projectId: "pr_java_dsa",
  },
  {
    id: "rec_3",
    title: "Practice Stack Problems",
    reason: "Your mastery is improving. Practice will help reach mastery.",
    priority: "Medium",
    estimatedMinutes: 25,
    type: "practice",
    projectId: "pr_java_dsa",
  },
  {
    id: "rec_4",
    title: "Take Adaptive Quiz",
    reason: "You haven't tested your understanding recently.",
    priority: "Medium",
    estimatedMinutes: 10,
    type: "quiz",
    projectId: "pr_ml_foundations",
  },
  {
    id: "rec_5",
    title: "Open-ended assessment: Binary Trees",
    reason: "Explaining traversals in your own words will expose remaining gaps.",
    priority: "Low",
    estimatedMinutes: 12,
    type: "assessment",
    projectId: "pr_java_dsa",
  },
];

export const activity: ActivityItem[] = [
  {
    id: "a_1",
    type: "quiz",
    title: "Completed Adaptive Quiz",
    detail: "Score: 82% · 8 of 10 correct",
    project: "Java DSA",
    day: "Today",
    time: "10:42",
  },
  {
    id: "a_2",
    type: "tutor",
    title: "Asked Tutor about Monotonic Stack",
    detail: "Grounded answer with 2 sources from Java DSA Notes.pdf",
    project: "Java DSA",
    day: "Today",
    time: "10:12",
  },
  {
    id: "a_3",
    type: "mastery",
    title: "Mastery increased: Stack +8%",
    detail: "78% mastery — status upgraded to Strong",
    project: "Java DSA",
    day: "Today",
    time: "10:45",
  },
  {
    id: "a_4",
    type: "upload",
    title: "Uploaded Java DSA PDF",
    detail: "Stack Problems.pdf · 42 pages · processing",
    project: "Java DSA",
    day: "Yesterday",
    time: "18:03",
  },
  {
    id: "a_5",
    type: "assessment",
    title: "Completed open-ended assessment",
    detail: "Understanding: 82% · Sliding Window",
    project: "Java DSA",
    day: "Yesterday",
    time: "17:20",
  },
  {
    id: "a_6",
    type: "tutor",
    title: "Asked Tutor about bias-variance tradeoff",
    detail: "Grounded answer with 1 source from ML Lecture Notes.pdf",
    project: "ML Foundations",
    day: "This week",
    time: "Wed 14:10",
  },
  {
    id: "a_7",
    type: "quiz",
    title: "Completed Adaptive Quiz",
    detail: "Score: 71% · 7 of 10 correct",
    project: "ML Foundations",
    day: "This week",
    time: "Tue 09:30",
  },
];

export const analytics: AnalyticsBundle = {
  totals: {
    studyTimeHours: 12.5,
    quizAccuracy: 82,
    conceptMastery: 74,
    questionsAnswered: 246,
    tutorQuestions: 58,
    streak: 7,
  },
  masteryTrend: [
    { label: "Week 1", mastery: 42 },
    { label: "Week 2", mastery: 51 },
    { label: "Week 3", mastery: 63 },
    { label: "Week 4", mastery: 74 },
  ],
  quizPerformance: [
    { label: "Quiz 1", accuracy: 58 },
    { label: "Quiz 2", accuracy: 64 },
    { label: "Quiz 3", accuracy: 71 },
    { label: "Quiz 4", accuracy: 76 },
    { label: "Quiz 5", accuracy: 82 },
  ],
  studyActivity: [
    { label: "Mon", minutes: 45 },
    { label: "Tue", minutes: 80 },
    { label: "Wed", minutes: 30 },
    { label: "Thu", minutes: 95 },
    { label: "Fri", minutes: 60 },
    { label: "Sat", minutes: 120 },
    { label: "Sun", minutes: 40 },
  ],
  conceptDistribution: [
    { name: "Mastered", value: 12 },
    { name: "Strong", value: 6 },
    { name: "Developing", value: 5 },
    { name: "Needs Review", value: 3 },
  ],
};

export const adminOverview: AdminOverview = {
  cards: [
    { label: "Total Users", value: "1,284", delta: "+64 this month" },
    { label: "Active Users", value: "812", delta: "+8.2% vs last week" },
    { label: "Total Projects", value: "3,946", delta: "+212 this month" },
    { label: "Total Materials", value: "9,178", delta: "+540 this month" },
    { label: "AI Requests", value: "128,430", delta: "+11.4% vs last week" },
    { label: "Average Quiz Score", value: "78%", delta: "+3 pts this month" },
  ],
  userActivity: [
    { label: "Mon", active: 612, new: 18 },
    { label: "Tue", active: 704, new: 22 },
    { label: "Wed", active: 668, new: 15 },
    { label: "Thu", active: 781, new: 31 },
    { label: "Fri", active: 812, new: 27 },
    { label: "Sat", active: 540, new: 12 },
    { label: "Sun", active: 498, new: 9 },
  ],
  projectActivity: [
    { label: "Mon", projects: 120 },
    { label: "Tue", projects: 168 },
    { label: "Wed", projects: 142 },
    { label: "Thu", projects: 196 },
    { label: "Fri", projects: 210 },
    { label: "Sat", projects: 98 },
    { label: "Sun", projects: 86 },
  ],
  aiUsage: [
    { label: "Mon", requests: 14200 },
    { label: "Tue", requests: 16850 },
    { label: "Wed", requests: 15320 },
    { label: "Thu", requests: 19410 },
    { label: "Fri", requests: 21030 },
    { label: "Sat", requests: 11240 },
    { label: "Sun", requests: 10380 },
  ],
  learningProgress: [
    { label: "Week 1", mastery: 54 },
    { label: "Week 2", mastery: 59 },
    { label: "Week 3", mastery: 66 },
    { label: "Week 4", mastery: 71 },
  ],
};

export const adminUsers: AdminUser[] = [
  {
    id: "u_1",
    name: "Yuvtej Sharma",
    email: "yuvtej@studymate.ai",
    spaces: 3,
    projects: 12,
    lastActive: "2 min ago",
    progress: 74,
    status: "Active",
  },
  {
    id: "u_2",
    name: "Ananya Rao",
    email: "ananya.rao@university.edu",
    spaces: 2,
    projects: 7,
    lastActive: "1 hr ago",
    progress: 66,
    status: "Active",
  },
  {
    id: "u_3",
    name: "Marcus Lee",
    email: "marcus.lee@university.edu",
    spaces: 4,
    projects: 15,
    lastActive: "Yesterday",
    progress: 81,
    status: "Active",
  },
  {
    id: "u_4",
    name: "Priya Nair",
    email: "priya.nair@university.edu",
    spaces: 1,
    projects: 2,
    lastActive: "6 days ago",
    progress: 24,
    status: "Invited",
  },
  {
    id: "u_5",
    name: "Tom Becker",
    email: "tom.becker@university.edu",
    spaces: 2,
    projects: 5,
    lastActive: "3 weeks ago",
    progress: 41,
    status: "Suspended",
  },
];

export const systemServices: SystemService[] = [
  { name: "API", status: "Healthy", detail: "p95 latency 180 ms", uptime: "99.98%" },
  { name: "Database", status: "Healthy", detail: "Connections 42 / 200", uptime: "99.99%" },
  {
    name: "AI Provider",
    status: "Warning",
    detail: "Elevated latency on evaluation model (2.4 s avg)",
    uptime: "99.42%",
  },
  {
    name: "Document Processing",
    status: "Healthy",
    detail: "6 documents in queue",
    uptime: "99.87%",
  },
  { name: "Background Jobs", status: "Healthy", detail: "No failed jobs in 24h", uptime: "99.95%" },
];

export const systemEvents = [
  {
    id: "e1",
    time: "08:42",
    level: "Warning",
    message: "AI evaluation latency above 2s threshold",
  },
  { id: "e2", time: "07:15", level: "Info", message: "Nightly mastery recalculation completed" },
  { id: "e3", time: "02:04", level: "Info", message: "Database backup completed (1.2 GB)" },
  {
    id: "e4",
    time: "Yesterday",
    level: "Error",
    message: "3 document processing jobs failed (OCR)",
  },
];

export const aiEvaluations = [
  {
    id: "ev1",
    question: "Explain monotonic stack with an example.",
    grounded: true,
    score: 94,
    project: "Java DSA",
    time: "10:12",
  },
  {
    id: "ev2",
    question: "How does the Transformer attention mechanism work?",
    grounded: false,
    score: 97,
    project: "Java DSA",
    time: "10:18",
  },
  {
    id: "ev3",
    question: "Difference between precision and recall?",
    grounded: true,
    score: 91,
    project: "ML Foundations",
    time: "09:44",
  },
  {
    id: "ev4",
    question: "Summarise chapter 4 of my notes.",
    grounded: true,
    score: 88,
    project: "Operating Systems",
    time: "09:02",
  },
];
