import type {
  ActivityItem,
  AdminOverview,
  AdminUser,
  AdminUserDetail,
  AnalyticsBundle,
  ChatMessageData,
  Concept,
  Conversation,
  KnowledgeNode,
  LearningPulse,
  Material,
  NotificationItem,
  Project,
  QuizQuestion,
  Recommendation,
  Space,
  SystemService,
  User,
} from "./types";

export const currentUser: User = {
  id: "u_1",
  name: "Yuvtej Sharma",
  email: "yuvtej@studymate.ai",
  role: "admin",
  avatarInitials: "YS",
  joinedAt: "2026-01-14",
};

export const spaces: Space[] = [
  {
    id: "sp_ml",
    name: "Machine Learning",
    description: "Supervised learning, optimisation and model evaluation — your primary space.",
    icon: "Brain",
    projectCount: 3,
    averageProgress: 64,
    materials: 7,
    studyTimeHours: 28.5,
    averageMastery: 63,
    lastActivity: "Today",
  },
  {
    id: "sp_dsa",
    name: "Data Structures",
    description: "Arrays, stacks, trees and the patterns behind common problems.",
    icon: "Boxes",
    projectCount: 2,
    averageProgress: 58,
    materials: 5,
    studyTimeHours: 16.0,
    averageMastery: 61,
    lastActivity: "Yesterday",
  },
  {
    id: "sp_genai",
    name: "Generative AI",
    description: "Transformers, prompting, retrieval and evaluation of generative systems.",
    icon: "Sparkles",
    projectCount: 2,
    averageProgress: 37,
    materials: 4,
    studyTimeHours: 9.5,
    averageMastery: 44,
    lastActivity: "3 days ago",
  },
  {
    id: "sp_interview",
    name: "Interview Preparation",
    description: "Timed practice, explanation drills and ML system design questions.",
    icon: "Target",
    projectCount: 2,
    averageProgress: 46,
    materials: 3,
    studyTimeHours: 11.0,
    averageMastery: 52,
    lastActivity: "2 days ago",
  },
];

export const projects: Project[] = [
  {
    id: "pr_ml_fundamentals",
    spaceId: "sp_ml",
    name: "Machine Learning Fundamentals",
    description: "Regression, classification, optimisation and evaluating models properly.",
    goal: "Understand ML fundamentals and confidently solve interview and practical problems.",
    subject: "Machine Learning",
    progress: 68,
    masteryScore: 63,
    conceptsMastered: 2,
    conceptCount: 7,
    materialCount: 3,
    quizAccuracy: 74,
    studyTimeHours: 14.5,
    status: "in-progress",
    lastActivity: "Today",
  },
  {
    id: "pr_deep_learning",
    spaceId: "sp_ml",
    name: "Deep Learning Basics",
    description: "Neural networks, backpropagation, activation functions and training loops.",
    goal: "Build a working intuition for how neural networks learn from data.",
    subject: "Machine Learning",
    progress: 41,
    masteryScore: 48,
    conceptsMastered: 3,
    conceptCount: 12,
    materialCount: 2,
    quizAccuracy: 66,
    studyTimeHours: 8.0,
    status: "needs-review",
    lastActivity: "Yesterday",
  },
  {
    id: "pr_ml_interview",
    spaceId: "sp_ml",
    name: "ML Interview Preparation",
    description: "Explaining trade-offs out loud: bias-variance, metrics and model choice.",
    goal: "Answer ML interview questions clearly, with correct reasoning and examples.",
    subject: "Machine Learning",
    progress: 52,
    masteryScore: 57,
    conceptsMastered: 4,
    conceptCount: 10,
    materialCount: 2,
    quizAccuracy: 70,
    studyTimeHours: 6.0,
    status: "in-progress",
    lastActivity: "2 days ago",
  },
  {
    id: "pr_dsa_core",
    spaceId: "sp_dsa",
    name: "Core Data Structures",
    description: "Arrays, hash maps, stacks, queues and tree traversals.",
    goal: "Recognise the right data structure for a problem within a minute.",
    subject: "Computer Science",
    progress: 62,
    masteryScore: 66,
    conceptsMastered: 8,
    conceptCount: 14,
    materialCount: 3,
    quizAccuracy: 79,
    studyTimeHours: 10.5,
    status: "in-progress",
    lastActivity: "Yesterday",
  },
  {
    id: "pr_transformers",
    spaceId: "sp_genai",
    name: "Transformers & LLMs",
    description: "Attention, embeddings, retrieval augmentation and evaluation.",
    goal: "Explain how modern language models are built and evaluated.",
    subject: "Generative AI",
    progress: 34,
    masteryScore: 42,
    conceptsMastered: 2,
    conceptCount: 11,
    materialCount: 2,
    quizAccuracy: 61,
    studyTimeHours: 5.5,
    status: "needs-review",
    lastActivity: "3 days ago",
  },
  {
    id: "pr_interview_drills",
    spaceId: "sp_interview",
    name: "Explanation Drills",
    description: "Open-ended answers graded on clarity, accuracy and reasoning.",
    goal: "Explain any core concept in under two minutes without notes.",
    subject: "Interview Preparation",
    progress: 88,
    masteryScore: 84,
    conceptsMastered: 9,
    conceptCount: 10,
    materialCount: 1,
    quizAccuracy: 86,
    studyTimeHours: 7.0,
    status: "completed",
    lastActivity: "2 days ago",
  },
];

export const materials: Material[] = [
  {
    id: "m_1",
    projectId: "pr_ml_fundamentals",
    name: "Machine Learning Notes.pdf",
    sizeMb: 5.4,
    pages: 148,
    status: "ready",
    stage: "Ready",
    uploadedAt: "2026-08-24",
  },
  {
    id: "m_2",
    projectId: "pr_ml_fundamentals",
    name: "Supervised Learning.pdf",
    sizeMb: 2.6,
    pages: 62,
    status: "ready",
    stage: "Ready",
    uploadedAt: "2026-09-01",
  },
  {
    id: "m_3",
    projectId: "pr_ml_fundamentals",
    name: "Model Evaluation.pdf",
    sizeMb: 3.1,
    pages: 74,
    status: "processing",
    stage: "Extracting Knowledge",
    progress: 68,
    uploadedAt: "2026-09-11",
  },
  {
    id: "m_4",
    projectId: "pr_ml_fundamentals",
    name: "Gradient Descent (scan).pdf",
    sizeMb: 8.7,
    pages: 0,
    status: "failed",
    error: "Text extraction failed — the PDF appears to be a low-quality scan.",
    uploadedAt: "2026-09-10",
  },
  {
    id: "m_5",
    projectId: "pr_deep_learning",
    name: "Neural Networks Primer.pdf",
    sizeMb: 6.2,
    pages: 122,
    status: "ready",
    stage: "Ready",
    uploadedAt: "2026-08-18",
  },
  {
    id: "m_6",
    projectId: "pr_ml_interview",
    name: "ML Interview Question Bank.pdf",
    sizeMb: 1.9,
    pages: 44,
    status: "ready",
    stage: "Ready",
    uploadedAt: "2026-09-04",
  },
];

export const concepts: Concept[] = [
  {
    id: "c_linear_regression",
    projectId: "pr_ml_fundamentals",
    name: "Linear Regression",
    mastery: 86,
    level: "Mastered",
    status: "Strong",
    weeklyChange: 4,
    quizzesTaken: 6,
    assessmentsTaken: 2,
    tutorQuestions: 9,
    lastPracticed: "Today",
    summary: "Fitting a straight-line relationship by minimising squared error.",
  },
  {
    id: "c_logistic_regression",
    projectId: "pr_ml_fundamentals",
    name: "Logistic Regression",
    mastery: 72,
    level: "Strong",
    status: "Improving",
    weeklyChange: 7,
    quizzesTaken: 5,
    assessmentsTaken: 1,
    tutorQuestions: 8,
    lastPracticed: "Today",
    summary: "Mapping a linear score to a probability with the sigmoid function.",
  },
  {
    id: "c_decision_trees",
    projectId: "pr_ml_fundamentals",
    name: "Decision Trees",
    mastery: 64,
    level: "Developing",
    status: "Stable",
    weeklyChange: 1,
    quizzesTaken: 4,
    assessmentsTaken: 1,
    tutorQuestions: 5,
    lastPracticed: "Yesterday",
    summary: "Recursive splits chosen by impurity reduction such as Gini or entropy.",
  },
  {
    id: "c_gradient_descent",
    projectId: "pr_ml_fundamentals",
    name: "Gradient Descent",
    mastery: 51,
    level: "Developing",
    status: "Needs Attention",
    weeklyChange: 9,
    quizzesTaken: 3,
    assessmentsTaken: 1,
    tutorQuestions: 12,
    lastPracticed: "Today",
    summary: "Iteratively stepping downhill along the gradient of the loss surface.",
  },
  {
    id: "c_cross_validation",
    projectId: "pr_ml_fundamentals",
    name: "Cross Validation",
    mastery: 58,
    level: "Developing",
    status: "Needs Attention",
    weeklyChange: 2,
    quizzesTaken: 3,
    assessmentsTaken: 0,
    tutorQuestions: 4,
    lastPracticed: "2 days ago",
    summary: "Rotating held-out folds to estimate generalisation more reliably.",
  },
  {
    id: "c_overfitting",
    projectId: "pr_ml_fundamentals",
    name: "Overfitting",
    mastery: 42,
    level: "Needs Review",
    status: "Needs Attention",
    weeklyChange: -3,
    quizzesTaken: 2,
    assessmentsTaken: 0,
    tutorQuestions: 6,
    lastPracticed: "4 days ago",
    summary: "Memorising training noise instead of learning the underlying signal.",
  },
  {
    id: "c_regularization",
    projectId: "pr_ml_fundamentals",
    name: "Regularization",
    mastery: 65,
    level: "Developing",
    status: "Improving",
    weeklyChange: 6,
    quizzesTaken: 3,
    assessmentsTaken: 1,
    tutorQuestions: 5,
    lastPracticed: "Yesterday",
    summary: "Penalising large weights (L1/L2) to trade a little bias for less variance.",
  },
];

export const knowledgeMap: KnowledgeNode[] = [
  {
    id: "k_supervised",
    projectId: "pr_ml_fundamentals",
    name: "Supervised Learning",
    description: "Learning a mapping from labelled inputs to outputs.",
    mastery: 71,
    document: "Machine Learning Notes.pdf",
    page: 8,
    related: ["Model Evaluation", "Overfitting"],
    children: [
      {
        id: "k_regression",
        projectId: "pr_ml_fundamentals",
        name: "Regression",
        description: "Predicting a continuous target value.",
        mastery: 79,
        document: "Supervised Learning.pdf",
        page: 12,
        related: ["Gradient Descent", "Regularization"],
        children: [
          {
            id: "k_linear_regression",
            projectId: "pr_ml_fundamentals",
            name: "Linear Regression",
            description: "Least-squares fit of a linear relationship.",
            mastery: 86,
            document: "Machine Learning Notes.pdf",
            page: 14,
            related: ["Gradient Descent", "Regularization"],
          },
        ],
      },
      {
        id: "k_classification",
        projectId: "pr_ml_fundamentals",
        name: "Classification",
        description: "Predicting a discrete class label.",
        mastery: 68,
        document: "Supervised Learning.pdf",
        page: 27,
        related: ["Model Evaluation", "Decision Trees"],
        children: [
          {
            id: "k_logistic_regression",
            projectId: "pr_ml_fundamentals",
            name: "Logistic Regression",
            description: "Sigmoid over a linear score, trained with log loss.",
            mastery: 72,
            document: "Supervised Learning.pdf",
            page: 31,
            related: ["Gradient Descent", "Cross Validation"],
          },
          {
            id: "k_decision_trees",
            projectId: "pr_ml_fundamentals",
            name: "Decision Trees",
            description: "Impurity-driven recursive partitioning of the feature space.",
            mastery: 64,
            document: "Supervised Learning.pdf",
            page: 41,
            related: ["Overfitting", "Regularization"],
          },
        ],
      },
    ],
  },
  {
    id: "k_optimization",
    projectId: "pr_ml_fundamentals",
    name: "Optimization",
    description: "How model parameters are actually found during training.",
    mastery: 54,
    document: "Machine Learning Notes.pdf",
    page: 52,
    related: ["Linear Regression", "Logistic Regression"],
    children: [
      {
        id: "k_gradient_descent",
        projectId: "pr_ml_fundamentals",
        name: "Gradient Descent",
        description: "Repeated parameter updates in the direction of steepest descent.",
        mastery: 51,
        document: "Machine Learning Notes.pdf",
        page: 55,
        related: ["Learning Rate", "Linear Regression"],
      },
      {
        id: "k_learning_rate",
        projectId: "pr_ml_fundamentals",
        name: "Learning Rate",
        description: "Step size controlling convergence speed and stability.",
        mastery: 57,
        document: "Machine Learning Notes.pdf",
        page: 58,
        related: ["Gradient Descent"],
      },
    ],
  },
  {
    id: "k_model_evaluation",
    projectId: "pr_ml_fundamentals",
    name: "Model Evaluation",
    description: "Measuring whether a model will generalise beyond training data.",
    mastery: 55,
    document: "Model Evaluation.pdf",
    page: 4,
    related: ["Cross Validation", "Overfitting"],
    children: [
      {
        id: "k_cross_validation",
        projectId: "pr_ml_fundamentals",
        name: "Cross Validation",
        description: "K-fold rotation of validation splits.",
        mastery: 58,
        document: "Model Evaluation.pdf",
        page: 9,
        related: ["Overfitting"],
      },
      {
        id: "k_overfitting",
        projectId: "pr_ml_fundamentals",
        name: "Overfitting",
        description: "Low training error with poor validation performance.",
        mastery: 42,
        document: "Model Evaluation.pdf",
        page: 18,
        related: ["Regularization", "Cross Validation"],
      },
      {
        id: "k_regularization",
        projectId: "pr_ml_fundamentals",
        name: "Regularization",
        description: "L1 and L2 penalties that shrink model weights.",
        mastery: 65,
        document: "Model Evaluation.pdf",
        page: 24,
        related: ["Overfitting", "Linear Regression"],
      },
    ],
  },
];

export const tutorConversation: ChatMessageData[] = [
  {
    id: "msg_1",
    role: "user",
    content: "Explain gradient descent simply.",
    createdAt: "10:12",
  },
  {
    id: "msg_2",
    role: "assistant",
    grounded: true,
    content:
      "Based on your uploaded material: gradient descent is how a model finds good parameter values. You start with random weights, measure how wrong the model is with a loss function, and then nudge each weight in the direction that reduces that loss.\n\nThe gradient tells you the direction of steepest increase, so you step the opposite way. The learning rate decides how big that step is — too small and training crawls, too large and the loss bounces around without settling.\n\nFor linear regression the loss surface is a smooth bowl, so repeated steps reliably reach the bottom. That is why your notes introduce it there first before applying it to logistic regression.",
    citations: [
      {
        id: "cit_1",
        document: "Machine Learning Notes.pdf",
        page: 55,
        excerpt:
          "Gradient descent updates each parameter by subtracting the learning rate times the partial derivative of the loss with respect to that parameter.",
      },
      {
        id: "cit_2",
        document: "Machine Learning Notes.pdf",
        page: 58,
        excerpt:
          "A learning rate that is too large causes the loss to oscillate or diverge; too small and convergence becomes impractically slow.",
      },
    ],
    createdAt: "10:12",
  },
  {
    id: "msg_3",
    role: "user",
    content: "How does the Transformer attention mechanism work?",
    createdAt: "10:18",
  },
  {
    id: "msg_4",
    role: "assistant",
    unsupported: true,
    content:
      "I couldn't find enough information in your Project materials to answer this reliably.",
    suggestions: ["Gradient Descent", "Cross Validation", "Regularization"],
    createdAt: "10:18",
  },
];

export const conversations: Conversation[] = [
  {
    id: "cv_1",
    projectId: "pr_ml_fundamentals",
    title: "Explain gradient descent simply",
    preview: "Gradient descent is how a model finds good parameter values…",
    concept: "Gradient Descent",
    messageCount: 8,
    grounded: true,
    updatedAt: "10:12",
    day: "Today",
  },
  {
    id: "cv_2",
    projectId: "pr_ml_fundamentals",
    title: "Compare L1 and L2 regularization",
    preview: "L1 drives some weights to exactly zero, L2 shrinks all of them smoothly…",
    concept: "Regularization",
    messageCount: 6,
    grounded: true,
    updatedAt: "09:38",
    day: "Today",
  },
  {
    id: "cv_3",
    projectId: "pr_ml_fundamentals",
    title: "Why does k-fold beat a single split?",
    preview: "Rotating folds averages out the luck of one particular validation split…",
    concept: "Cross Validation",
    messageCount: 5,
    grounded: true,
    updatedAt: "18:04",
    day: "Yesterday",
  },
  {
    id: "cv_4",
    projectId: "pr_ml_fundamentals",
    title: "How do I spot overfitting early?",
    preview: "Watch validation loss rise while training loss keeps falling…",
    concept: "Overfitting",
    messageCount: 11,
    grounded: true,
    updatedAt: "Wed 14:22",
    day: "This week",
  },
  {
    id: "cv_5",
    projectId: "pr_ml_fundamentals",
    title: "Transformer attention question",
    preview: "Not covered by your project materials — suggested related topics instead.",
    concept: "Unsupported",
    messageCount: 2,
    grounded: false,
    updatedAt: "Mon 11:05",
    day: "Earlier",
  },
  {
    id: "cv_6",
    projectId: "pr_ml_fundamentals",
    title: "Decision tree splitting criteria",
    preview: "Gini impurity and entropy both measure how mixed a node's labels are…",
    concept: "Decision Trees",
    messageCount: 7,
    grounded: true,
    updatedAt: "Mon 09:12",
    day: "Earlier",
  },
];

export const quizQuestions: QuizQuestion[] = [
  {
    id: "q1",
    concept: "Gradient Descent",
    difficulty: "Medium",
    prompt: "What does the learning rate control in gradient descent?",
    options: [
      { id: "a", text: "The number of training examples used per epoch." },
      { id: "b", text: "The size of each parameter update step." },
      { id: "c", text: "The number of features in the model." },
      { id: "d", text: "The regularization penalty applied to weights." },
    ],
    correctOptionId: "b",
    explanation:
      "The learning rate multiplies the gradient, so it sets how far parameters move on each update.",
  },
  {
    id: "q2",
    concept: "Gradient Descent",
    difficulty: "Hard",
    prompt: "Training loss oscillates wildly and never settles. What is the most likely cause?",
    options: [
      { id: "a", text: "The learning rate is too large." },
      { id: "b", text: "The dataset is too small." },
      { id: "c", text: "The model has too few parameters." },
      { id: "d", text: "The features are already normalised." },
    ],
    correctOptionId: "a",
    explanation: "Oversized steps overshoot the minimum repeatedly, so the loss bounces.",
  },
  {
    id: "q3",
    concept: "Linear Regression",
    difficulty: "Easy",
    prompt: "Which loss function is standard for linear regression?",
    options: [
      { id: "a", text: "Cross entropy" },
      { id: "b", text: "Hinge loss" },
      { id: "c", text: "Mean squared error" },
      { id: "d", text: "Gini impurity" },
    ],
    correctOptionId: "c",
    explanation: "Least squares minimises the mean squared difference between prediction and target.",
  },
  {
    id: "q4",
    concept: "Logistic Regression",
    difficulty: "Medium",
    prompt: "What does the sigmoid function do in logistic regression?",
    options: [
      { id: "a", text: "It squashes a linear score into a probability between 0 and 1." },
      { id: "b", text: "It sorts the training data by label." },
      { id: "c", text: "It removes correlated features." },
      { id: "d", text: "It computes the impurity of a split." },
    ],
    correctOptionId: "a",
    explanation: "Sigmoid maps any real number onto (0, 1), which is interpreted as a probability.",
  },
  {
    id: "q5",
    concept: "Overfitting",
    difficulty: "Easy",
    prompt: "Which pattern most clearly indicates overfitting?",
    options: [
      { id: "a", text: "Training and validation loss both stay high." },
      { id: "b", text: "Training loss falls while validation loss rises." },
      { id: "c", text: "Validation accuracy exceeds training accuracy." },
      { id: "d", text: "Loss decreases smoothly on both splits." },
    ],
    correctOptionId: "b",
    explanation: "The model is fitting noise specific to the training set.",
  },
  {
    id: "q6",
    concept: "Overfitting",
    difficulty: "Medium",
    prompt: "Which change is least likely to reduce overfitting?",
    options: [
      { id: "a", text: "Adding L2 regularization" },
      { id: "b", text: "Collecting more training data" },
      { id: "c", text: "Increasing model capacity" },
      { id: "d", text: "Early stopping" },
    ],
    correctOptionId: "c",
    explanation: "More capacity gives the model more room to memorise the training set.",
  },
  {
    id: "q7",
    concept: "Cross Validation",
    difficulty: "Medium",
    prompt: "In 5-fold cross validation, how many models are trained?",
    options: [
      { id: "a", text: "1" },
      { id: "b", text: "4" },
      { id: "c", text: "5" },
      { id: "d", text: "25" },
    ],
    correctOptionId: "c",
    explanation: "Each fold takes a turn as the validation set, so five models are trained.",
  },
  {
    id: "q8",
    concept: "Regularization",
    difficulty: "Hard",
    prompt: "What distinguishes L1 from L2 regularization?",
    options: [
      { id: "a", text: "L1 can drive weights to exactly zero; L2 shrinks them smoothly." },
      { id: "b", text: "L1 only applies to classification models." },
      { id: "c", text: "L2 removes features before training." },
      { id: "d", text: "There is no practical difference." },
    ],
    correctOptionId: "a",
    explanation: "The absolute-value penalty produces sparse solutions; the squared penalty does not.",
  },
  {
    id: "q9",
    concept: "Decision Trees",
    difficulty: "Medium",
    prompt: "What does a decision tree optimise when choosing a split?",
    options: [
      { id: "a", text: "The distance between cluster centroids" },
      { id: "b", text: "The reduction in impurity, such as Gini or entropy" },
      { id: "c", text: "The magnitude of the weight vector" },
      { id: "d", text: "The learning rate schedule" },
    ],
    correctOptionId: "b",
    explanation: "Each split is picked to make the resulting child nodes as pure as possible.",
  },
  {
    id: "q10",
    concept: "Cross Validation",
    difficulty: "Hard",
    prompt: "Why should scaling be fitted inside each cross-validation fold?",
    options: [
      { id: "a", text: "To speed up training" },
      { id: "b", text: "To avoid leaking validation statistics into training" },
      { id: "c", text: "Because scaling is required by decision trees" },
      { id: "d", text: "To reduce the number of folds needed" },
    ],
    correctOptionId: "b",
    explanation: "Fitting the scaler on all data leaks validation information and inflates scores.",
  },
];

export const openEndedPrompt =
  "In your own words, explain how gradient descent finds good model parameters, and describe what happens when the learning rate is set too high or too low.";

export const recommendations: Recommendation[] = [
  {
    id: "rec_1",
    title: "Take 5-question Gradient Descent quiz",
    reason: "Gradient Descent is your weakest concept at 51% but improved 9% this week.",
    priority: "High",
    estimatedMinutes: 10,
    type: "quiz",
    projectId: "pr_ml_fundamentals",
  },
  {
    id: "rec_2",
    title: "Review Overfitting",
    reason: "Mastery slipped 3% this week and two quiz answers were incorrect.",
    priority: "High",
    estimatedMinutes: 15,
    type: "review",
    projectId: "pr_ml_fundamentals",
  },
  {
    id: "rec_3",
    title: "Practice Cross Validation",
    reason: "You have not practised k-fold validation in two days.",
    priority: "Medium",
    estimatedMinutes: 20,
    type: "practice",
    projectId: "pr_ml_fundamentals",
  },
  {
    id: "rec_4",
    title: "Open-ended assessment: Regularization",
    reason: "Explaining L1 versus L2 out loud will expose remaining gaps.",
    priority: "Medium",
    estimatedMinutes: 12,
    type: "assessment",
    projectId: "pr_ml_fundamentals",
  },
  {
    id: "rec_5",
    title: "Take Adaptive Quiz",
    reason: "You haven't tested Deep Learning Basics recently.",
    priority: "Low",
    estimatedMinutes: 10,
    type: "quiz",
    projectId: "pr_deep_learning",
  },
];

export const learningPulse: LearningPulse = {
  currentFocus: "Gradient Descent",
  strongest: { name: "Linear Regression", mastery: 86 },
  weakest: { name: "Gradient Descent", mastery: 51 },
  weeklyImprovement: 9,
  nextAction: {
    label: "Take 5-question Gradient Descent quiz",
    description: "Ten minutes of focused practice on your weakest concept.",
    projectId: "pr_ml_fundamentals",
    concept: "Gradient Descent",
  },
};

export const activity: ActivityItem[] = [
  {
    id: "a_1",
    type: "quiz",
    title: "Completed Adaptive Quiz",
    detail: "Score: 74% · 7 of 10 correct",
    project: "Machine Learning Fundamentals",
    day: "Today",
    time: "10:42",
  },
  {
    id: "a_2",
    type: "tutor",
    title: "Asked Tutor about Gradient Descent",
    detail: "Grounded answer with 2 sources from Machine Learning Notes.pdf",
    project: "Machine Learning Fundamentals",
    day: "Today",
    time: "10:12",
  },
  {
    id: "a_3",
    type: "mastery",
    title: "Mastery increased: Gradient Descent +9%",
    detail: "51% mastery — still flagged as Needs Attention",
    project: "Machine Learning Fundamentals",
    day: "Today",
    time: "10:45",
  },
  {
    id: "a_4",
    type: "upload",
    title: "Uploaded Model Evaluation.pdf",
    detail: "74 pages · extracting knowledge",
    project: "Machine Learning Fundamentals",
    day: "Yesterday",
    time: "18:03",
  },
  {
    id: "a_5",
    type: "assessment",
    title: "Completed open-ended assessment",
    detail: "Understanding: 78% · Regularization",
    project: "Machine Learning Fundamentals",
    day: "Yesterday",
    time: "17:20",
  },
  {
    id: "a_6",
    type: "tutor",
    title: "Asked Tutor about k-fold validation",
    detail: "Grounded answer with 1 source from Model Evaluation.pdf",
    project: "Machine Learning Fundamentals",
    day: "This week",
    time: "Wed 14:10",
  },
  {
    id: "a_7",
    type: "quiz",
    title: "Completed Adaptive Quiz",
    detail: "Score: 66% · 6 of 9 correct",
    project: "Deep Learning Basics",
    day: "This week",
    time: "Tue 09:30",
  },
];

export const notifications: NotificationItem[] = [
  {
    id: "n1",
    type: "processing",
    title: "Document processing update",
    detail: "Model Evaluation.pdf — extracting knowledge (68%)",
    time: "8m ago",
    read: false,
  },
  {
    id: "n2",
    type: "mastery",
    title: "Mastery milestone",
    detail: "Gradient Descent improved 9% this week",
    time: "1h ago",
    read: false,
  },
  {
    id: "n3",
    type: "quiz",
    title: "Suggested quiz",
    detail: "5 questions on Overfitting — your weakest trend",
    time: "3h ago",
    read: false,
  },
  {
    id: "n4",
    type: "processing",
    title: "Processing failed",
    detail: "Gradient Descent (scan).pdf could not be read — retry available",
    time: "Yesterday",
    read: true,
  },
  {
    id: "n5",
    type: "mastery",
    title: "Concept mastered",
    detail: "Linear Regression reached 86%",
    time: "2 days ago",
    read: true,
  },
];

export const analytics: AnalyticsBundle = {
  totals: {
    studyTimeHours: 14.5,
    quizAccuracy: 74,
    conceptMastery: 63,
    questionsAnswered: 218,
    tutorQuestions: 49,
    streak: 7,
  },
  masteryTrend: [
    { label: "Week 1", mastery: 38 },
    { label: "Week 2", mastery: 47 },
    { label: "Week 3", mastery: 56 },
    { label: "Week 4", mastery: 63 },
  ],
  quizPerformance: [
    { label: "Quiz 1", accuracy: 52 },
    { label: "Quiz 2", accuracy: 61 },
    { label: "Quiz 3", accuracy: 68 },
    { label: "Quiz 4", accuracy: 70 },
    { label: "Quiz 5", accuracy: 74 },
  ],
  studyActivity: [
    { label: "Mon", minutes: 50 },
    { label: "Tue", minutes: 85 },
    { label: "Wed", minutes: 35 },
    { label: "Thu", minutes: 100 },
    { label: "Fri", minutes: 65 },
    { label: "Sat", minutes: 115 },
    { label: "Sun", minutes: 45 },
  ],
  conceptDistribution: [
    { name: "Mastered", value: 1 },
    { name: "Strong", value: 1 },
    { name: "Developing", value: 4 },
    { name: "Needs Review", value: 1 },
  ],
};

export const adminOverview: AdminOverview = {
  cards: [
    { label: "Total Users", value: "1,284", delta: "+64 this month" },
    { label: "Active Users", value: "812", delta: "+8.2% vs last week" },
    { label: "Total Projects", value: "3,946", delta: "+212 this month" },
    { label: "Total Materials", value: "9,178", delta: "+540 this month" },
    { label: "AI Requests", value: "128,430", delta: "+11.4% vs last week" },
    { label: "Average Quiz Score", value: "76%", delta: "+3 pts this month" },
  ],
  userActivity: [
    { label: "Mon", active: 612, new: 18 },
    { label: "Tue", active: 704, new: 22 },
    { label: "Wed", active: 668, new: 15 },
    { label: "Thu", active: 781, new: 31 },
    { label: "Fri", active: 812, new: 27 },
    { label: "Sat", active: 540, new: 12 },
    { label: "Sun", active: 498, new: 9 },
  ],
  projectActivity: [
    { label: "Mon", projects: 120 },
    { label: "Tue", projects: 168 },
    { label: "Wed", projects: 142 },
    { label: "Thu", projects: 196 },
    { label: "Fri", projects: 210 },
    { label: "Sat", projects: 98 },
    { label: "Sun", projects: 86 },
  ],
  aiUsage: [
    { label: "Mon", requests: 14200 },
    { label: "Tue", requests: 16850 },
    { label: "Wed", requests: 15320 },
    { label: "Thu", requests: 19410 },
    { label: "Fri", requests: 21030 },
    { label: "Sat", requests: 11240 },
    { label: "Sun", requests: 10380 },
  ],
  learningProgress: [
    { label: "Week 1", mastery: 54 },
    { label: "Week 2", mastery: 59 },
    { label: "Week 3", mastery: 66 },
    { label: "Week 4", mastery: 71 },
  ],
};

export const adminUsers: AdminUser[] = [
  {
    id: "u_1",
    name: "Yuvtej Sharma",
    email: "yuvtej@studymate.ai",
    spaces: 4,
    projects: 6,
    lastActive: "2 min ago",
    progress: 63,
    status: "Active",
  },
  {
    id: "u_2",
    name: "Ananya Rao",
    email: "ananya.rao@university.edu",
    spaces: 2,
    projects: 7,
    lastActive: "1 hr ago",
    progress: 66,
    status: "Active",
  },
  {
    id: "u_3",
    name: "Marcus Lee",
    email: "marcus.lee@university.edu",
    spaces: 4,
    projects: 15,
    lastActive: "Yesterday",
    progress: 81,
    status: "Active",
  },
  {
    id: "u_4",
    name: "Priya Nair",
    email: "priya.nair@university.edu",
    spaces: 1,
    projects: 2,
    lastActive: "6 days ago",
    progress: 24,
    status: "Invited",
  },
  {
    id: "u_5",
    name: "Tom Becker",
    email: "tom.becker@university.edu",
    spaces: 2,
    projects: 5,
    lastActive: "3 weeks ago",
    progress: 41,
    status: "Suspended",
  },
];

function buildUserDetail(user: AdminUser, seed: number): AdminUserDetail {
  return {
    ...user,
    joinedAt: "2026-01-14",
    role: user.id === "u_1" ? "admin" : "student",
    studyTimeHours: Math.round((12 + seed * 6.5) * 10) / 10,
    streak: 3 + seed,
    tokensUsed: 184_000 + seed * 46_300,
    tokenCostUsd: Math.round((3.6 + seed * 1.15) * 100) / 100,
    aiRequests: 420 + seed * 137,
    groundingRate: 90 + ((seed * 3) % 8),
    projectList: [
      { id: "pr_ml_fundamentals", name: "Machine Learning Fundamentals", progress: 68, mastery: 63 },
      { id: "pr_deep_learning", name: "Deep Learning Basics", progress: 41, mastery: 48 },
      { id: "pr_ml_interview", name: "ML Interview Preparation", progress: 52, mastery: 57 },
    ],
    quizHistory: [
      { id: "qh1", title: "Adaptive Quiz", concept: "Gradient Descent", score: 74, date: "Today" },
      { id: "qh2", title: "Recommended Quiz", concept: "Overfitting", score: 60, date: "Yesterday" },
      { id: "qh3", title: "Adaptive Quiz", concept: "Regularization", score: 82, date: "Wed" },
      { id: "qh4", title: "Adaptive Quiz", concept: "Cross Validation", score: 68, date: "Mon" },
    ],
    masteryTrend: [
      { label: "Week 1", mastery: 38 },
      { label: "Week 2", mastery: 47 },
      { label: "Week 3", mastery: 56 },
      { label: "Week 4", mastery: user.progress },
    ],
    tokenTrend: [
      { label: "Mon", tokens: 18_400 },
      { label: "Tue", tokens: 24_800 },
      { label: "Wed", tokens: 16_200 },
      { label: "Thu", tokens: 31_050 },
      { label: "Fri", tokens: 28_700 },
      { label: "Sat", tokens: 12_900 },
      { label: "Sun", tokens: 9_800 },
    ],
    timeline: activity,
  };
}

export const adminUserDetails: AdminUserDetail[] = adminUsers.map((u, i) => buildUserDetail(u, i));

export const systemServices: SystemService[] = [
  { name: "API", status: "Healthy", detail: "p95 latency 180 ms", uptime: "99.98%" },
  { name: "Database", status: "Healthy", detail: "Connections 42 / 200", uptime: "99.99%" },
  {
    name: "AI Provider",
    status: "Warning",
    detail: "Elevated latency on evaluation model (2.4 s avg)",
    uptime: "99.42%",
  },
  {
    name: "Document Processing",
    status: "Healthy",
    detail: "6 documents in queue",
    uptime: "99.87%",
  },
  { name: "Background Jobs", status: "Healthy", detail: "No failed jobs in 24h", uptime: "99.95%" },
];

export const systemEvents = [
  { id: "e1", time: "08:42", level: "Warning", message: "AI evaluation latency above 2s threshold" },
  { id: "e2", time: "07:15", level: "Info", message: "Nightly mastery recalculation completed" },
  { id: "e3", time: "02:04", level: "Info", message: "Database backup completed (1.2 GB)" },
  { id: "e4", time: "Yesterday", level: "Error", message: "3 document processing jobs failed (OCR)" },
];

export const aiEvaluations = [
  {
    id: "ev1",
    question: "Explain gradient descent simply.",
    grounded: true,
    score: 94,
    project: "Machine Learning Fundamentals",
    time: "10:12",
  },
  {
    id: "ev2",
    question: "How does the Transformer attention mechanism work?",
    grounded: false,
    score: 97,
    project: "Machine Learning Fundamentals",
    time: "10:18",
  },
  {
    id: "ev3",
    question: "Difference between precision and recall?",
    grounded: true,
    score: 91,
    project: "ML Interview Preparation",
    time: "09:44",
  },
  {
    id: "ev4",
    question: "Summarise chapter 4 of my notes.",
    grounded: true,
    score: 88,
    project: "Deep Learning Basics",
    time: "09:02",
  },
];
